controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

welcome:
    path: /
    controller: App\Controller\WelcomeController::index

# Explicit routes for SecurityController based on the provided code
security:
    resource: ../src/Controller/SecurityController.php
    type: attribute

home:
    path: /
    controller: App\Controller\WelcomeController::index

regulations_list:
    path: /regulations
    controller: App\Controller\RegulationController::list

# Explicit routes for QuestionController based on the provided code
questions_list:
    path: /question/
    controller: App\Controller\QuestionController::list
    methods: [GET]

question_new:
    path: /question/new
    controller: App\Controller\QuestionController::create
    methods: [GET, POST]

question_edit:
    path: /question/{id}/edit
    controller: App\Controller\QuestionController::edit
    methods: [GET, POST]

question_delete:
    path: /question/{id}
    controller: App\Controller\QuestionController::delete
    methods: [POST]

# Explicit routes for EvaluationController based on the provided code
evaluation_index:
    path: /evaluation/
    controller: App\Controller\EvaluationController::list
    methods: [GET]

evaluation_new:
    path: /evaluation/new
    controller: App\Controller\EvaluationController::create
    methods: [GET, POST]

evaluation_show:
    path: /evaluation/new
    controller: App\Controller\EvaluationController::show
    methods: [GET, POST]

evaluation_delete:
    path: /evaluation/{id}
    controller: App\Controller\EvaluationController::delete
    methods: [POST]

# Example route for user profile (you'll need to create this controller)
profile:
    path: /profile
    controller: App\Controller\WelcomeController::index
    # You might want to add security requirements to this route
    # requirements:
    #     _security: is_granted('ROLE_USER')

app_logout:
    path: /logout
    controller: App\Controller\WelcomeController::logout